CREATE DATABASE theRichCity CHARACTER SET = gb2312;

CREATE TABLE theRichCity.t_user (
	uuid BIGINT UNSIGNED AUTO_INCREMENT,
	nme VARCHAR(20) NOT NULL UNIQUE,
	eml VARCHAR(30) NOT NULL UNIQUE,
	pwd VARCHAR(20) NOT NULL,
	score LONG,
	rgst_dt DATETIME NOT NULL,
    lst_updt_tme TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY(uuid)
);


CREATE TABLE theRichCity.t_board (
	uuid TINYINT UNSIGNED PRIMARY KEY,
	isStarted BOOLEAN NOT NULL,
	crt_dt DATETIME NOT NULL,
	maxPlayers TINYINT UNSIGNED NOT NULL,
    lst_updt_tme TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE theRichCity.t_userboard (
	uuid INT UNSIGNED,
	usr BIGINT UNSIGNED NOT NULL UNIQUE REFERENCES t_user.uuid,
	board TINYINT UNSIGNED NOT NULL REFERENCES t_board.uuid,
	is_host BOOL NOT NULL,
	crt_dt DATETIME NOT NULL,
    lst_updt_tme TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY(uuid)
);


GRANT ALL PRIVILEGES ON theRichCity.* TO 'AmyChris'@'%'  IDENTIFIED BY '123456';